#include "Hackathon-2App.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<Hackathon-2App>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

Hackathon-2App::Hackathon-2App(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  Hackathon-2App::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  Hackathon-2App::associateSyntax(_syntax, _action_factory);
}

Hackathon-2App::~Hackathon-2App()
{
}

// External entry point for dynamic application loading
extern "C" void Hackathon-2App__registerApps() { Hackathon-2App::registerApps(); }
void
Hackathon-2App::registerApps()
{
  registerApp(Hackathon-2App);
}

// External entry point for dynamic object registration
extern "C" void Hackathon-2App__registerObjects(Factory & factory) { Hackathon-2App::registerObjects(factory); }
void
Hackathon-2App::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void Hackathon-2App__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { Hackathon-2App::associateSyntax(syntax, action_factory); }
void
Hackathon-2App::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
